/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * HeartEnvite
 * The HeartEnvite API description
 * OpenAPI spec version: 3.0
 */
import type { CardcaptionEntity } from './cardcaptionEntity';

export interface CardEntity {
  id: number;
  cardName?: string;
  cardCategory: string;
  description: string;
  cardDetails: string[];
  cardTemplates: string[];
  cardTotalPrice: number;
  cardSalePrice?: number;
  noOfPages: number;
  cardReligion?: string;
  Caption: CardcaptionEntity;
}
