/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * HeartEnvite
 * The HeartEnvite API description
 * OpenAPI spec version: 3.0
 */

export type CardetailsControllerGetCardsByPriceParams = { range?: number; religion1?: string; religion2?: string; religion3?: string; religion4?: string };
