/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * HeartEnvite
 * The HeartEnvite API description
 * OpenAPI spec version: 3.0
 */
import type { CardEntity } from './cardEntity';

export interface CardcaptionEntity {
  id: number;
  Card: CardEntity;
  page: string;
  previewPage: string;
  Caption: string[];
}
