/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * HeartEnvite
 * The HeartEnvite API description
 * OpenAPI spec version: 3.0
 */

export interface CardDto {
  id: number;
  email: string;
  details: string[];
  userId: string;
  maxCharsPerLine: number;
  minCharsPerLine: number;
}
