/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * HeartEnvite
 * The HeartEnvite API description
 * OpenAPI spec version: 3.0
 */

export interface CreateUserDto {
  firstName: string;
  lastName?: string;
  email: string;
  password: string;
}
