/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * HeartEnvite
 * The HeartEnvite API description
 * OpenAPI spec version: 3.0
 */

export interface CreateCardetailDto {
  cardName: string;
  description: string;
  cardCategory: string;
  cardTotalPrice: number;
  cardDetails: string[];
  cardTemplates: string[];
  cardSalePrice?: number;
  cardReligion?: string;
  noOfPages: number;
}
