/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * HeartEnvite
 * The HeartEnvite API description
 * OpenAPI spec version: 3.0
 */
import type { UserCardEntityTextItem } from './userCardEntityTextItem';

export interface UserCardEntity {
  id: string;
  cardCategory: string;
  description: string;
  email: string;
  cardNames: string[];
  previewCardNames: string[];
  cardId: number;
  userId: string;
  paymentStatus: string;
  text?: UserCardEntityTextItem[];
  cardTotalPrice: number;
  cardSalePrice: number;
  noOfPages: number;
  orderCreationId?: string;
  razorpayPaymentId?: string;
  razorpayOrderId?: string;
  paymentDate?: string;
  createdAt: string;
  updatedAt: string;
}
