/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * HeartEnvite
 * The HeartEnvite API description
 * OpenAPI spec version: 3.0
 */

export interface User {
  id: string;
  firstName: string;
  lastName?: string;
  email: string;
  phoneNumber?: string;
  profileImage?: string;
  active: boolean;
  role: string;
  password?: string;
  provider?: string;
  createdAt: string;
  updatedAt: string;
}
