/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * HeartEnvite
 * The HeartEnvite API description
 * OpenAPI spec version: 3.0
 */

export interface VideoDto {
  id: number;
  Details: string[];
  text: string;
}
