import { useFonts } from "expo-font";

export const useFontsLoaded = () => {
  let [fontsLoaded] = useFonts({
    "AGaramondPro-Bold": require("./font/AGaramondPro-Bold.ttf"),
    "Ananda-Black": require("./font/Ananda-Black-Personal-Use.ttf"),
    "arial-mt-bold": require("./font/arial-mt-bold.ttf"),
    ArialMT: require("./font/ArialMT.ttf"),
    "ArimaMadurai-Bold": require("./font/ArimaMadurai-Bold.ttf"),
    BELLB: require("./font/BELLB.ttf"),
    BOD_B: require("./font/BOD_B.ttf"),
    BodoniMT: require("./font/BodoniMT.ttf"),
    cac_champagne: require("./font/cac_champagne.ttf"),
    CopperplateGothicLight: require("./font/CopperplateGothicLight.ttf"),
    "Franklin-Gothic-Medium-Regular": require("./font/Franklin-Gothic-Medium-Regular.ttf"),
    "FuzzyBubbles-Regular": require("./font/FuzzyBubbles-Regular.ttf"),
    Gabriola: require("./font/Gabriola.ttf"),
    gadugi: require("./font/gadugi.ttf"),
    gadugib: require("./font/gadugib.ttf"),
    Georgia: require("./font/Georgia.ttf"),
    "georgia-bold": require("./font/georgia-bold.ttf"),
    "GreatVibes-Regular": require("./font/GreatVibes-Regular.ttf"),
    "JosefinSans-Regular": require("./font/JosefinSans-Regular.ttf"),
    LBRITED: require("./font/LBRITED.ttf"),
    LCALLIG: require("./font/LCALLIG.ttf"),
    LSANSD: require("./font/LSANSD.ttf"),
    "Lucida-Fax-Demibold-Italic": require("./font/Lucida-Fax-Demibold-Italic.ttf"),
    "Lucida-Handwriting-Italic": require("./font/Lucida-Handwriting-Italic.ttf"),
    "Lucida-Sans-Regular": require("./font/Lucida-Sans-Regular.ttf"),
    LucidaFaxDemibold: require("./font/LucidaFaxDemibold.ttf"),
    "MinionPro-Regular": require("./font/MinionPro-Regular.ttf"),
    "MinionPro-Semibold": require("./font/MinionPro-Semibold.ttf"),
    "Mongolian-Baiti-Regular": require("./font/Mongolian-Baiti-Regular.ttf"),
    "Monotype-Corsiva": require("./font/Monotype-Corsiva.ttf"),
    "Montserrat-Bold": require("./font/Montserrat-Bold.ttf"),
    "Myriad-Pro-Bold": require("./font/Myriad-Pro-Bold.ttf"),
    "Myriad-Pro-Bold-Italic": require("./font/Myriad-Pro-Bold-Italic.ttf"),
    "Myriad-Pro-Bold-SemiExtended": require("./font/Myriad-Pro-Bold-SemiExtended.ttf"),
    "Myriad-Pro-Condensed": require("./font/Myriad-Pro-Condensed.ttf"),
    "Myriad-Pro-Light": require("./font/Myriad-Pro-Light.ttf"),
    "Myriad-Pro-Regular": require("./font/Myriad-Pro-Regular.ttf"),
    "Myriad-Pro-Semibold": require("./font/Myriad-Pro-Semibold.ttf"),
    Nirmala: require("./font/Nirmala.ttf"),
    NirmalaB: require("./font/NirmalaB.ttf"),
    NirmalaS: require("./font/NirmalaS.ttf"),
    ntailu: require("./font/ntailu.ttf"),
    ntailub: require("./font/ntailub.ttf"),
    "NuevaStd-Bold": require("./font/NuevaStd-Bold.ttf"),
    palab: require("./font/palab.ttf"),
    PRISTINA: require("./font/PRISTINA.ttf"),
    qkmarisa: require("./font/qkmarisa.ttf"),
    Romelio: require("./font/Romelio.ttf"),
    "Segoe-UI-Bold": require("./font/Segoe-UI-Bold.ttf"),
  });

  return fontsLoaded;
};
